name: Node.js CI

on: [push]

jobs:
  # run `npm test`
  test:
    name: npm test
    strategy:
      fail-fast: false
      matrix:
        node-version: ['16.x', '18.x', '20.x']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  # run the test script in src/script.js (prove this is unrelated to `node --test`)
  script:
    name: node src/script.js
    strategy:
      fail-fast: false
      matrix:
        node-version: ['16.x', '18.x', '20.x']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: node src/script.js
